export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';

export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPE_FAIL = 'FETCH_RECIPE_FAIL';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';

export const ADD_INSTRUCTION = 'ADD_INSTRUCTION';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INSTRUCTION = 'DELETE_INSTRUCTION';
export const EDIT_INSTRUCTION = 'EDIT_INSTRUCTION';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT';
export const MAP_RECIPE_TO_EDIT = 'MAP_RECIPE_TO_EDIT';
export const LIST_EDIT = 'LIST_EDIT';
export const CLEAR_ADD_RECIPE_FORM = 'CLEAR_ADD_RECIPE_FORM';

export const FETCH_SCHEDULE_START = 'FETCH_SCHEDULE_START';
export const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS';
export const FETCH_SCHEDULE_FAIL = 'FETCH_SCHEDULE_FAIL';
export const ADD_SCHEDULE_SUCCESS = 'ADD_SCHEDULE_SUCCESS';
export const SET_SCHEDULE_TO_SHOW = 'SET_SCHEDULE_TO_SHOW';

export const MAP_SCHEDULE_TO_EDIT = 'MAP_SCHEDULE_TO_EDIT';
export const CLEAR_ADD_SCHEDULE_FORM = 'CLEAR_ADD_SCHEDULE_FORM';
